### PR TITLE
scaffold exhibitions archive

### PR DESCRIPTION
**Pull request by varffs**

### CODE REVIEW

**Comment by mixcas** [comment]
noup

**Comment by mixcas** [comment]
noup

screen shot 2016-03-30 at 2 33 50 pm

**Comment by varffs** [comment]
this is fine. its a scaffold. any logic for masonry or css to fix heights will happen later

**Comment by varffs** [comment]
@mixcas oi!

**Comment by mixcas** [comment]
mmmkay

**Pull request merged**
